#!/bin/sh

if [ "$FOOTER_BROWSE_SD" = "true" ]; then
	cmds="$(cat << EOF
root $ROOTDEV
browse
EOF
)"
	write_entry "Browse SD" "$cmds"
fi

if [ "$FOOTER_BOOTMII" = "true" ]; then
	cmds="$(cat << EOF
root $ROOTDEV
kernel /bootmii/gui.elf
EOF
)"
	write_entry "BootMii GUI" "$cmds"
fi

if [ "$FOOTER_POWER" = "true" ]; then
	write_entry "Reboot" "reboot"
	write_entry "Power Off" "poweroff"
fi
